{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep.fullname" . }}-frontend
  labels:
    {{- include "keep.labels" . | nindent 4 }}
    keep-component: frontend-service
  annotations:
    {{- if .Values.isGKE }}
    cloud.google.com/backend-config: '{"default": "{{ include "keep.fullname" . }}-frontend-backendconfig"}'
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
    {{- if .Values.frontend.extraPorts }}
    {{- toYaml .Values.frontend.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "keep.selectorLabels" . | nindent 4 }}
    keep-component: frontend
{{- end }}
